run:
  timeout: 5m
  go: '1.19'
linters:
  enable:
    - containedctx
    - gofmt
    - dogsled
    - errorlint
#    - gci
    - nilnil
    - noctx
exclude-rules:
  # Independently of option `exclude` we use default exclude patterns,
  # it can be disabled by this option.
  # To list all excluded by default patterns execute `golangci-lint run --help`.
  # Default: true.
  exclude-use-default: false