name: CI
on:
  # always execute docker build when something is pushed to main or a maintenance branch
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
  # in addition, execute for pull requests to those branches
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
env:
  GO_VERSION: "~1.19"
  CONTROLLER_TOOLS_VERSION: "v0.9.2"
  ENVTEST_K8S_VERSION: "1.24.2"
  SCHEDULER_COMPATIBLE_K8S_VERSION: "v0.24.3"
defaults:
  run:
    shell: bash

jobs:
  prepare_ci_run:
    name: Prepare CI Run
    runs-on: ubuntu-22.04
    outputs:
      GIT_SHA: ${{ steps.extract_branch.outputs.GIT_SHA }}
      BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
      BRANCH_SLUG: ${{ steps.extract_branch.outputs.BRANCH_SLUG }}
      DATETIME: ${{ steps.get_datetime.outputs.DATETIME }}
      BUILD_TIME: ${{ steps.get_datetime.outputs.BUILD_TIME }}
      NON_FORKED_AND_NON_ROBOT_RUN: ${{ steps.get_run_type.outputs.NON_FORKED_AND_NON_ROBOT_RUN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        uses: keptn/gh-action-extract-branch-name@main

      - name: Get current date and time
        id: get_datetime
        run: |
          DATETIME=$(date +'%Y%m%d%H%M')
          BUILD_TIME=$(date -u "+%F_%T")
          echo "DATETIME=$DATETIME" >> "$GITHUB_OUTPUT"
          echo "BUILD_TIME=$BUILD_TIME" >> "$GITHUB_OUTPUT"

      - name: Get workflow run type
        id: get_run_type
        run: |
          NON_FORKED_AND_NON_ROBOT_RUN=${{ ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository ) }}
          echo "github.actor != 'renovate[bot]' = ${{ github.actor != 'renovate[bot]' }}"
          echo "github.actor != 'dependabot[bot]' = ${{ github.actor != 'dependabot[bot]' }}"
          echo "github.event_name == 'push' = ${{ github.event_name == 'push' }}"
          echo "github.event.pull_request.head.repo.full_name == github.repository = ${{ github.event.pull_request.head.repo.full_name == github.repository }}"
          echo "NON_FORKED_AND_NON_ROBOT_RUN = $NON_FORKED_AND_NON_ROBOT_RUN"
          echo "NON_FORKED_AND_NON_ROBOT_RUN=$NON_FORKED_AND_NON_ROBOT_RUN" >> "$GITHUB_OUTPUT"

  format:
    name: Go format check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Format check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; 
          then 
            exit 1; 
          fi

  test:
    name: Unit Tests
    needs: [ prepare_ci_run, format ]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
            # Nothing to test in functions-runtime
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '${{ matrix.config.folder }}go.sum'

      - name: Test ${{ matrix.config.name }}
        working-directory: ./${{ matrix.config.folder }}
        run: make test

      - name: Report code coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.config.name }}

  build_image:
    name: Build Docker Image
    needs: [ prepare_ci_run, format ]
    runs-on: ubuntu-22.04
    env:
      BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
      DATETIME: ${{ needs.prepare_ci_run.outputs.DATETIME }}
      BUILD_TIME: ${{ needs.prepare_ci_run.outputs.BUILD_TIME }}
      GIT_SHA: ${{ needs.prepare_ci_run.outputs.GIT_SHA }}
      RELEASE_REGISTRY: "localhost:5000/keptn"
    strategy:
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
          - name: "functions-runtime"
            folder: "functions-runtime/"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2      

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.config.folder }}
          platforms: linux/amd64
          target: production
          tags: |
            ${{ env.RELEASE_REGISTRY }}/${{ matrix.config.name }}:dev-${{ env.DATETIME }}
          build-args: |
            GIT_HASH=${{ env.GIT_SHA }}
            RELEASE_VERSION=dev-${{ env.DATETIME }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            CONTROLLER_TOOLS_VERSION=${{ env.CONTROLLER_TOOLS_VERSION }}
            SCHEDULER_COMPATIBLE_K8S_VERSION=${{ env.SCHEDULER_COMPATIBLE_K8S_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          outputs: type=docker,dest=/tmp/${{ matrix.config.name }}-image.tar
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.name }}-image.tar
          path: /tmp/${{ matrix.config.name }}-image.tar

      - name: Install controller-gen
        if: matrix.config.name == 'keptn-lifecycle-operator'
        working-directory: ./${{ matrix.config.folder }}
        run: make controller-gen

      - name: Generate release.yaml
        if: matrix.config.name != 'functions-runtime'
        working-directory: ./${{ matrix.config.folder }}
        env:
          TAG: dev-${{ env.DATETIME }}
        run: make release-manifests

      - name: Upload release.yaml for tests
        if: matrix.config.name != 'functions-runtime'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.name }}-manifest-test
          path: ${{ matrix.config.folder }}/config/rendered/release.yaml

  component_tests:
    name: Component Tests
    needs: [ prepare_ci_run, format ]
    uses: ./.github/workflows/component-test.yml

  integration_tests:
    name: Integration Tests
    needs: [ prepare_ci_run, build_image ]
    uses: ./.github/workflows/integration-test.yml

  e2e_tests:
    name: End to End Tests
    needs: [ prepare_ci_run, build_image ]
    uses: ./.github/workflows/e2e-test.yml

  performance_tests:
    name: Performance Tests
    needs: [ prepare_ci_run, build_image ]
    uses: ./.github/workflows/performance-test.yml

  upload_images:
    name: Upload images to ghcr registry
    needs: [prepare_ci_run, test, component_tests, integration_tests, e2e_tests, performance_tests]
    if: github.event_name == 'push' && needs.prepare_ci_run.outputs.NON_FORKED_AND_NON_ROBOT_RUN == 'true' # only run on push to main/maintenance branches
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
          - name: "functions-runtime"
            folder: "functions-runtime/"
    permissions:
      packages: write # Needed for pushing images to the registry
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2  

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.config.folder }}
        platforms: linux/amd64,linux/arm64
        target: production
        tags: |
          ghcr.io/keptn/${{ matrix.config.name }}:dev-${{ env.DATETIME }}
        build-args: |
          GIT_HASH=${{ env.GIT_SHA }}
          RELEASE_VERSION=dev-${{ env.DATETIME }}
          BUILD_TIME=${{ env.BUILD_TIME }}
          CONTROLLER_TOOLS_VERSION=${{ env.CONTROLLER_TOOLS_VERSION }}
          SCHEDULER_COMPATIBLE_K8S_VERSION=${{ env.SCHEDULER_COMPATIBLE_K8S_VERSION }}
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, scope=${{ github.workflow }}

    - name: Install controller-gen
      if: matrix.config.name == 'keptn-lifecycle-operator'
      working-directory: ./${{ matrix.config.folder }}
      run: make controller-gen

    - name: Generate release.yaml
      if: matrix.config.name != 'functions-runtime'
      working-directory: ./${{ matrix.config.folder }}
      env:
        TAG: dev-${{ env.DATETIME }}
      run: make release-manifests

    - name: Upload release.yaml
      if: matrix.config.name != 'functions-runtime'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}-manifest
        path: ${{ matrix.config.folder }}/config/rendered/release.yaml
