name: golangci-lint
on: pull_request
env:
  GOLANGCI_LINT_VERSION: "v1.50.1"
jobs:
  golangci-lint:
    name: reviewdog
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ matrix.config.folder }}
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 5m -E gofmt -E containedctx -E dogsled -E errorlint -E gci -E nilnil -E noctx
