name: Integration-Test
on:
  workflow_call:
    inputs:
      functions_runtime_tag:
        description: "Tag for the functions runner image"
        type: "string"
        required: true
env:
  GO_VERSION: "~1.19"
  # renovate: datasource=github-releases depName=cert-manager/cert-manager
  KUTTL_VERSION: "0.13.0"
defaults:
  run:
    shell: bash

jobs:
  run-integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup cluster
        uses: ./.github/actions/deploy-klt-on-cluster
        with:
          functions_runtime_tag: ${{ inputs.functions_runtime_tag }}

      - name: Download KUTTL
        run: |
          curl -fL https://github.com/kudobuilder/kuttl/releases/download/v${{ env.KUTTL_VERSION }}/kubectl-kuttl_${{ env.KUTTL_VERSION }}_linux_x86_64 -o kubectl-kuttl
          chmod +x kubectl-kuttl
          mv kubectl-kuttl /usr/local/bin

      - name: Run Integration Tests
        working-directory: .
        run: make integration-test
