name: Performance Tests
on:
  workflow_call:
    inputs:
      functions_runtime_tag:
        description: "Tag for the functions runner image"
        type: "string"
        required: true
env:
  GO_VERSION: "~1.19"
  USE_EXISTING_CLUSTER: "true"
defaults:
  run:
    shell: bash
jobs:
  performance_tests:
    name: Performance Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup cluster
      uses: ./.github/actions/deploy-klt-on-cluster
      with:
        functions_runtime_tag: ${{ inputs.functions_runtime_tag }}

    - name: Execute Performance Tests
      working-directory: operator
      run: |
        make performance-test
