name: Performance Tests
on:
  workflow_call:
env:
  GO_VERSION: "~1.19"
  CERT_MANAGER_VERSION: "v1.10.0"
  USE_EXISTING_CLUSTER: "true"
  K3D_VERSION: "v5.4.6"
defaults:
  run:
    shell: bash
jobs:
  performance_tests:
    name: Performance Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup cluster
      uses: ./.github/actions/deploy-klt-on-cluster
      with:
        cert-manager-version: ${{ env.CERT_MANAGER_VERSION }}
        k3d-version: ${{ env.K3D_VERSION }}

    - name: Execute Performance Tests
      working-directory: operator
      run: |
        make performance-test
