name: reviewdog
on: pull_request
env:
  GOLANGCI_LINT_VERSION: v.1.50.1
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ${{ matrix.config.folder }}
          golangci_lint_flags: "--enable-all --exclude-use-default=false --timeout 5m"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          go_version: "1.19"
