name: reviewdog
on: pull_request
env:
  GOLANGCI_LINT_VERSION: v.1.50.1
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          level: warning
          golangci_lint_flags: "--enable-all --exclude-use-default=false ./operator/controllers"
