name: reviewdog
on: pull_request
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2